"use client";
import {FormEvent,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {apiFetch,isAuthError} from "../../lib/api";

export default function Learning(){
 const router=useRouter();const [me,setMe]=useState<any>(null);const [courses,setCourses]=useState<any[]>([]);const [sections,setSections]=useState<any[]>([]);const [courseId,setCourseId]=useState("");const [assignments,setAssignments]=useState<any[]>([]);const [assessments,setAssessments]=useState<any[]>([]);const [results,setResults]=useState<any[]>([]);const [roster,setRoster]=useState<any[]>([]);
 const [courseForm,setCourseForm]=useState({section_id:"",teacher_id:"",name:""});const [assignmentForm,setAssignmentForm]=useState({title:"",instructions:"",max_marks:"100",due_at:""});const [assessmentForm,setAssessmentForm]=useState({name:"",max_marks:"100"});const [submission,setSubmission]=useState<Record<string,string>>({});const [marks,setMarks]=useState<Record<string,string>>({});const [error,setError]=useState("");const [message,setMessage]=useState("");
 async function load(){try{const [u,c]=await Promise.all([apiFetch("/auth/me"),apiFetch("/courses")]);setMe(u.data);setCourses(c.data);if(u.data.permissions.includes("learning.course.manage"))setSections((await apiFetch("/attendance/sections")).data);if(u.data.permissions.includes("learning.course.view"))setResults((await apiFetch("/assessment-results")).data)}catch(e){if(isAuthError(e))router.replace("/login");else setError(e instanceof Error?e.message:"Unable to load learning workspace")}}
 useEffect(()=>{load()},[]);
 async function selectCourse(id:string){setCourseId(id);setAssignments([]);setAssessments([]);setRoster([]);setMarks({});if(!id)return;try{const [a,s]=await Promise.all([apiFetch("/assignments?course_id="+id),apiFetch("/assessments?course_id="+id)]);setAssignments(a.data);setAssessments(s.data);if(me?.permissions?.includes("assessment.marks.manage"))setRoster((await apiFetch("/courses/"+id+"/roster")).data)}catch(e){setError(e instanceof Error?e.message:"Unable to load course workspace")}}
 async function createCourse(e:FormEvent){e.preventDefault();setError("");try{await apiFetch("/courses",{method:"POST",body:JSON.stringify({...courseForm,teacher_id:courseForm.teacher_id||null})});setCourseForm({section_id:"",teacher_id:"",name:""});setMessage("Course created.");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to create course")}}
 async function createAssignment(e:FormEvent){e.preventDefault();try{await apiFetch("/assignments",{method:"POST",body:JSON.stringify({course_id:courseId,title:assignmentForm.title,instructions:assignmentForm.instructions||null,max_marks:Number(assignmentForm.max_marks),due_at:assignmentForm.due_at||null})});setAssignmentForm({title:"",instructions:"",max_marks:"100",due_at:""});setMessage("Assignment created.");await selectCourse(courseId)}catch(e){setError(e instanceof Error?e.message:"Unable to create assignment")}}
 async function publishAssignment(id:string){try{await apiFetch("/assignments/"+id+"/publish",{method:"POST"});setMessage("Assignment published.");await selectCourse(courseId)}catch(e){setError(e instanceof Error?e.message:"Unable to publish assignment")}}
 async function createAssessment(e:FormEvent){e.preventDefault();try{await apiFetch("/assessments",{method:"POST",body:JSON.stringify({course_id:courseId,name:assessmentForm.name,max_marks:Number(assessmentForm.max_marks)})});setAssessmentForm({name:"",max_marks:"100"});setMessage("Assessment created.");await selectCourse(courseId)}catch(e){setError(e instanceof Error?e.message:"Unable to create assessment")}}
 async function saveMarks(assessmentId:string,maxMarks:number){try{const payload=roster.map(x=>({student_id:x.student_id,marks:Number(marks[x.student_id]||0)}));if(payload.some(x=>x.marks<0||x.marks>maxMarks))throw new Error("Marks outside assessment range");await apiFetch("/assessments/"+assessmentId+"/marks",{method:"PUT",body:JSON.stringify(payload)});setMessage("Marks saved.")}catch(e){setError(e instanceof Error?e.message:"Unable to save marks")}}
 async function publishAssessment(id:string){try{await apiFetch("/assessments/"+id+"/publish",{method:"POST"});setMessage("Assessment published.");await selectCourse(courseId)}catch(e){setError(e instanceof Error?e.message:"Unable to publish assessment")}}
 async function submitAssignment(id:string){const studentId=me?.scopes?.find((x:any)=>x.role==="STUDENT"&&x.scope_type==="STUDENT")?.scope_id;if(!studentId){setError("Student scope is not linked.");return}try{await apiFetch("/assignments/"+id+"/submissions",{method:"POST",body:JSON.stringify({student_id:studentId,content:submission[id]||""})});setMessage("Assignment submitted.")}catch(e){setError(e instanceof Error?e.message:"Unable to submit assignment")}}
 const p=me?.permissions||[];const canCourse=p.includes("learning.course.manage"),canAssignment=p.includes("learning.assignment.manage"),canAssessment=p.includes("assessment.manage"),canMarks=p.includes("assessment.marks.manage"),canSubmit=p.includes("learning.submission.create");
 return <main className="module-page"><header><div><p className="eyebrow">LEARNING & ASSESSMENT</p><h1>Learning Workspace</h1><p className="muted">Permission-scoped courses, assignments, submissions and assessments.</p></div><button className="secondary" onClick={()=>router.push("/dashboard")}>Dashboard</button></header>{message&&<p className="status">{message}</p>}{error&&<p className="error">{error}</p>}
 {canCourse&&<section className="panel"><h2>Create course</h2><form className="module-form" onSubmit={createCourse}><label>Section<select value={courseForm.section_id} onChange={e=>setCourseForm({...courseForm,section_id:e.target.value})} required><option value="">Select section</option>{sections.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label>Course name<input value={courseForm.name} onChange={e=>setCourseForm({...courseForm,name:e.target.value})} required/></label><button>Create course</button></form></section>}
 <section className="panel" style={{marginTop:18}}><h2>Courses</h2>{courses.length?<select value={courseId} onChange={e=>selectCourse(e.target.value)}><option value="">Select course</option>{courses.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>:<p className="muted">No courses available.</p>}</section>
 {courseId&&<section className="two-column" style={{marginTop:18}}><section className="panel"><h2>Assignments</h2>{canAssignment&&<form onSubmit={createAssignment}><label>Title<input value={assignmentForm.title} onChange={e=>setAssignmentForm({...assignmentForm,title:e.target.value})} required/></label><label>Instructions<textarea value={assignmentForm.instructions} onChange={e=>setAssignmentForm({...assignmentForm,instructions:e.target.value})}/></label><label>Max marks<input type="number" min="1" value={assignmentForm.max_marks} onChange={e=>setAssignmentForm({...assignmentForm,max_marks:e.target.value})}/></label><label>Due at<input type="datetime-local" value={assignmentForm.due_at} onChange={e=>setAssignmentForm({...assignmentForm,due_at:e.target.value})}/></label><button>Create assignment</button></form>}{assignments.length?assignments.map(a=><div className="simple-row" key={a.id}><span><strong>{a.title}</strong><small>{a.status} · Max {a.max_marks}</small>{canSubmit&&<><textarea placeholder="Submission" value={submission[a.id]||""} onChange={e=>setSubmission({...submission,[a.id]:e.target.value})}/><button onClick={()=>submitAssignment(a.id)}>Submit</button></>}</span>{canAssignment&&a.status==="DRAFT"&&<button onClick={()=>publishAssignment(a.id)}>Publish</button>}</div>):<p className="muted">No assignments.</p>}</section>
 <section className="panel"><h2>Assessments</h2>{canAssessment&&<form onSubmit={createAssessment}><label>Name<input value={assessmentForm.name} onChange={e=>setAssessmentForm({...assessmentForm,name:e.target.value})} required/></label><label>Max marks<input type="number" min="1" value={assessmentForm.max_marks} onChange={e=>setAssessmentForm({...assessmentForm,max_marks:e.target.value})}/></label><button>Create assessment</button></form>}{assessments.length?assessments.map(a=><div key={a.id}><div className="simple-row"><span><strong>{a.name}</strong><small>{a.status} · Max {a.max_marks}</small></span>{canAssessment&&a.status==="DRAFT"&&<button onClick={()=>publishAssessment(a.id)}>Publish</button>}</div>{canMarks&&a.status==="DRAFT"&&<div>{roster.map(x=><label key={x.student_id}>{x.name}<input type="number" min="0" max={a.max_marks} value={marks[x.student_id]||""} onChange={e=>setMarks({...marks,[x.student_id]:e.target.value})}/></label>)}<button onClick={()=>saveMarks(a.id,a.max_marks)}>Save marks</button></div>}</div>):<p className="muted">No assessments.</p>}</section></section>}
 {!canAssessment&&results.length>0&&<section className="panel" style={{marginTop:18}}><h2>Published results</h2>{results.map((x:any)=><div className="simple-row" key={x.assessment_id+"-"+x.student_id}><strong>{x.assessment_name}</strong><span>{x.marks} / {x.max_marks}</span></div>)}</section>}
 </main>}