"use client";
import {FormEvent,useEffect,useState} from "react";import {useRouter} from "next/navigation";import {apiFetch,isAuthError} from "../../lib/api";
export default function Staff(){const router=useRouter();const [rows,setRows]=useState<any[]>([]);const [me,setMe]=useState<any>(null);const [f,setF]=useState({employee_no:"",name:"",email:"",designation:""});const [selected,setSelected]=useState<any>(null);const [teacher,setTeacher]=useState({email:"",password:""});const [years,setYears]=useState<any[]>([]);const [classes,setClasses]=useState<any[]>([]);const [sections,setSections]=useState<any[]>([]);const [assignment,setAssignment]=useState({academic_year_id:"",class_id:"",section_id:""});const [msg,setMsg]=useState("");const [error,setError]=useState("");
async function load(){try{const [staff,user,ys]=await Promise.all([apiFetch("/staff"),apiFetch("/auth/me"),apiFetch("/academics/years")]);setRows(staff.data);setMe(user.data);setYears(ys.data)}catch(e){if(isAuthError(e))router.replace("/login");else setError(e instanceof Error?e.message:"Unable to load staff")}}useEffect(()=>{load()},[]);
async function submit(e:FormEvent){e.preventDefault();setError("");try{await apiFetch("/staff",{method:"POST",body:JSON.stringify({...f,email:f.email||null,designation:f.designation||null})});setF({employee_no:"",name:"",email:"",designation:""});setMsg("Staff created.");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to create staff")}}
async function chooseYear(id:string){setAssignment({academic_year_id:id,class_id:"",section_id:""});setClasses([]);setSections([]);if(id)setClasses((await apiFetch("/academics/classes?academic_year_id="+id)).data)}
async function chooseClass(id:string){setAssignment({...assignment,class_id:id,section_id:""});setSections([]);if(id)setSections((await apiFetch("/academics/sections?class_id="+id)).data)}
async function createTeacher(e:FormEvent){e.preventDefault();if(!selected)return;setError("");try{await apiFetch("/staff/"+selected.id+"/teacher-account",{method:"POST",body:JSON.stringify(teacher)});setTeacher({email:"",password:""});setMsg("Teacher login created with STAFF scope.")}catch(e){setError(e instanceof Error?e.message:"Unable to create teacher account")}}
async function assignTeacher(e:FormEvent){e.preventDefault();if(!selected)return;setError("");try{await apiFetch("/staff/"+selected.id+"/assignments",{method:"POST",body:JSON.stringify({section_id:assignment.section_id,assignment_type:"CLASS_TEACHER"})});setMsg("Teacher assigned to section.")}catch(e){setError(e instanceof Error?e.message:"Unable to assign teacher")}}
const canCreate=me?.permissions?.includes("staff.staff.create");const canProvision=me?.permissions?.includes("users.user.create");const canAssign=me?.permissions?.includes("academics.setup.admin");
return <main className="module-page"><header><div><p className="eyebrow">STAFF MANAGEMENT</p><h1>Staff</h1><p className="muted">Manage institution staff, teacher accounts and section assignments.</p></div><button className="secondary" onClick={()=>router.push("/dashboard")}>Dashboard</button></header>{msg&&<p className="status">{msg}</p>}{error&&<p className="error">{error}</p>}
<section className={canCreate?"two-column":"profile-grid"}>{canCreate&&<form className="panel" onSubmit={submit}><h2>Add staff</h2><label>Employee No<input value={f.employee_no} onChange={e=>setF({...f,employee_no:e.target.value})} required/></label><label>Name<input value={f.name} onChange={e=>setF({...f,name:e.target.value})} required/></label><label>Email<input type="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/></label><label>Designation<input value={f.designation} onChange={e=>setF({...f,designation:e.target.value})}/></label><button>Add staff</button></form>}<section className="panel"><h2>Staff directory</h2>{rows.length?rows.map(x=><button className="simple-row" key={x.id} onClick={()=>setSelected(x)}><span><strong>{x.name}</strong><small>{x.employee_no} • {x.designation||"Staff"}</small></span><span className="status-pill">{x.status}</span></button>):<p className="muted">No staff yet.</p>}</section></section>
{selected&&(canProvision||canAssign)&&<section className="two-column" style={{marginTop:18}}>{canProvision&&<form className="panel" onSubmit={createTeacher}><h2>Create teacher login</h2><p className="muted">{selected.name} · {selected.employee_no}</p><label>Login email<input type="email" value={teacher.email} onChange={e=>setTeacher({...teacher,email:e.target.value})} required/></label><label>Temporary password<input type="password" minLength={10} value={teacher.password} onChange={e=>setTeacher({...teacher,password:e.target.value})} required/></label><button>Create teacher account</button></form>}
{canAssign&&<form className="panel" onSubmit={assignTeacher}><h2>Assign teacher to section</h2><p className="muted">{selected.name} · {selected.employee_no}</p><label>Academic year<select value={assignment.academic_year_id} onChange={e=>chooseYear(e.target.value)} required><option value="">Select year</option>{years.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select></label><label>Class<select value={assignment.class_id} onChange={e=>chooseClass(e.target.value)} required disabled={!assignment.academic_year_id}><option value="">Select class</option>{classes.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Section<select value={assignment.section_id} onChange={e=>setAssignment({...assignment,section_id:e.target.value})} required disabled={!assignment.class_id}><option value="">Select section</option>{sections.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><button>Assign section</button></form>}</section>}</main>}