"""academic and student foundation"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="0003_core_academics"; down_revision="0002_sessions"; branch_labels=None; depends_on=None
def upgrade():
    op.create_table("academic_years",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("tenant_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("tenants.id"),nullable=False),sa.Column("name",sa.String(80),nullable=False),sa.Column("start_date",sa.Date(),nullable=False),sa.Column("end_date",sa.Date(),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.UniqueConstraint("tenant_id","name"))
    op.create_table("academic_classes",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("tenant_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("tenants.id"),nullable=False),sa.Column("academic_year_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("academic_years.id"),nullable=False),sa.Column("name",sa.String(100),nullable=False),sa.UniqueConstraint("tenant_id","academic_year_id","name"))
    op.create_table("sections",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("tenant_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("tenants.id"),nullable=False),sa.Column("class_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("academic_classes.id"),nullable=False),sa.Column("name",sa.String(80),nullable=False),sa.UniqueConstraint("tenant_id","class_id","name"))
    op.create_table("students",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("tenant_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("tenants.id"),nullable=False),sa.Column("admission_no",sa.String(80),nullable=False),sa.Column("first_name",sa.String(120),nullable=False),sa.Column("last_name",sa.String(120)),sa.Column("email",sa.String(320)),sa.Column("status",sa.String(30),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","admission_no"))
    op.create_table("enrollments",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("tenant_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("tenants.id"),nullable=False),sa.Column("student_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("students.id"),nullable=False),sa.Column("academic_year_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("academic_years.id"),nullable=False),sa.Column("class_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("academic_classes.id"),nullable=False),sa.Column("section_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("sections.id"),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.UniqueConstraint("tenant_id","student_id","academic_year_id"))
def downgrade():
    for t in ["enrollments","students","sections","academic_classes","academic_years"]: op.drop_table(t)
