"""learning assessment"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="0006_learning_assessment";down_revision="0005_timetable_attendance";branch_labels=None;depends_on=None
def upgrade():
 op.create_table("courses",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("tenant_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("tenants.id"),nullable=False),sa.Column("section_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("sections.id"),nullable=False),sa.Column("teacher_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("staff.id")),sa.Column("name",sa.String(160),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.UniqueConstraint("tenant_id","section_id","name"))
 op.create_table("assignments",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("tenant_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("tenants.id"),nullable=False),sa.Column("course_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("courses.id"),nullable=False),sa.Column("title",sa.String(180),nullable=False),sa.Column("instructions",sa.Text()),sa.Column("max_marks",sa.Integer(),nullable=False),sa.Column("due_at",sa.DateTime(timezone=True)),sa.Column("status",sa.String(30),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 op.create_table("submissions",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("tenant_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("tenants.id"),nullable=False),sa.Column("assignment_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("assignments.id"),nullable=False),sa.Column("student_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("students.id"),nullable=False),sa.Column("content",sa.Text()),sa.Column("status",sa.String(30),nullable=False),sa.Column("submitted_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","assignment_id","student_id"))
 op.create_table("assessments",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("tenant_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("tenants.id"),nullable=False),sa.Column("course_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("courses.id"),nullable=False),sa.Column("name",sa.String(180),nullable=False),sa.Column("max_marks",sa.Integer(),nullable=False),sa.Column("status",sa.String(30),nullable=False))
 op.create_table("assessment_marks",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("tenant_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("tenants.id"),nullable=False),sa.Column("assessment_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("assessments.id"),nullable=False),sa.Column("student_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("students.id"),nullable=False),sa.Column("marks",sa.Integer(),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.UniqueConstraint("tenant_id","assessment_id","student_id"))
def downgrade():
 for t in ["assessment_marks","assessments","submissions","assignments","courses"]:op.drop_table(t)
