"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {apiFetch,isAuthError} from "../../lib/api";
export default function Reports(){
 const router=useRouter();type Summary={students:number;staff:number;active_enrollments:number;absence_records:number;finance:{billed:string;paid:string;outstanding:string}};
 const [d,setD]=useState<Summary|null>(null);const [me,setMe]=useState<any>(null);const [events,setEvents]=useState<any[]>([]);const [error,setError]=useState("");
 useEffect(()=>{(async()=>{try{const [summary,user]=await Promise.all([apiFetch("/reports/summary"),apiFetch("/auth/me")]);setD(summary.data);setMe(user.data);if(user.data.permissions.includes("audit.event.view"))setEvents((await apiFetch("/reports/audit-events")).data)}catch(e){if(isAuthError(e))router.replace("/login");else setError(e instanceof Error?e.message:"Unable to load report")}})()},[router]);
 return <main className="module-page"><header><div><p className="eyebrow">MIS & REPORTS</p><h1>Summary</h1><p className="muted">Permission-scoped operational snapshot.</p></div><button className="secondary" onClick={()=>router.push("/dashboard")}>Dashboard</button></header>{error?<p className="error">{error}</p>:d?<><section className="profile-grid"><article className="panel"><h2>People & Academics</h2><dl><dt>Students</dt><dd>{d.students}</dd><dt>Staff</dt><dd>{d.staff}</dd><dt>Enrollments</dt><dd>{d.active_enrollments}</dd><dt>Absences</dt><dd>{d.absence_records}</dd></dl></article><article className="panel"><h2>Finance</h2><dl><dt>Billed</dt><dd>₹ {d.finance.billed}</dd><dt>Paid</dt><dd>₹ {d.finance.paid}</dd><dt>Outstanding</dt><dd>₹ {d.finance.outstanding}</dd></dl></article></section>{me?.permissions?.includes("audit.event.view")&&<section className="panel" style={{marginTop:18}}><h2>Audit events</h2><p className="muted">Read-only tenant audit trail. Latest 100 events.</p>{events.length?events.map(x=><div className="simple-row" key={x.id}><span><strong>{x.action}</strong><small>{x.resource_type}{x.resource_id?" · "+x.resource_id:""} · {new Date(x.created_at).toLocaleString()}</small></span><span className="status-pill">{x.user_id?"USER":"SYSTEM"}</span></div>):<p className="muted">No audit events available.</p>}</section>}</>:<p className="loading">Loading report…</p>}</main>
}