"use client";
import {FormEvent,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {apiFetch,isAuthError} from "../../lib/api";

export default function Communication(){
 const router=useRouter();const [f,setF]=useState({title:"",body:"",audience:"ALL"});const [drafts,setDrafts]=useState<any[]>([]);const [rows,setRows]=useState<any[]>([]);const [notifications,setNotifications]=useState<any[]>([]);const [me,setMe]=useState<any>(null);const [error,setError]=useState("");const [message,setMessage]=useState("");
 async function load(){try{const [notices,user,notes]=await Promise.all([apiFetch("/notices"),apiFetch("/auth/me"),apiFetch("/notifications")]);setRows(notices.data);setMe(user.data);setNotifications(notes.data);if(user.data.permissions.includes("communication.notice.manage"))setDrafts((await apiFetch("/notices/drafts")).data)}catch(e){if(isAuthError(e))router.replace("/login");else setError(e instanceof Error?e.message:"Unable to load notices")}}useEffect(()=>{load()},[]);
 async function submit(e:FormEvent){e.preventDefault();setError("");try{await apiFetch("/notices",{method:"POST",body:JSON.stringify(f)});setF({title:"",body:"",audience:"ALL"});setMessage("Notice draft created.");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to create notice")}}
 async function publish(id:string){setError("");try{await apiFetch("/notices/"+id+"/publish",{method:"POST"});setMessage("Notice published.");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to publish notice")}}
 async function markRead(id:string){try{await apiFetch("/notifications/"+id+"/read",{method:"POST"});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to mark notification read")}}
 const p=me?.permissions||[];const canManage=p.includes("communication.notice.manage"),canPublish=p.includes("communication.notice.publish");
 return <main className="module-page"><header><div><p className="eyebrow">COMMUNICATION</p><h1>Notices</h1><p className="muted">{canManage?"Draft, review and publish institution announcements.":"Published notices and notifications available to your role."}</p></div><button className="secondary" onClick={()=>router.push("/dashboard")}>Dashboard</button></header>{message&&<p className="status">{message}</p>}{error&&<p className="error">{error}</p>}
 {canManage&&<section className="two-column"><form className="panel" onSubmit={submit}><h2>New notice</h2><label>Title<input value={f.title} onChange={e=>setF({...f,title:e.target.value})} required/></label><label>Audience<select value={f.audience} onChange={e=>setF({...f,audience:e.target.value})}><option>ALL</option><option>STUDENT</option><option>PARENT</option><option>TEACHER</option><option>STAFF</option></select></label><label>Message<textarea value={f.body} onChange={e=>setF({...f,body:e.target.value})} required/></label><button>Create draft</button></form>
 <section className="panel"><h2>Drafts</h2>{drafts.length?drafts.map(x=><div className="simple-row" key={x.id}><span><strong>{x.title}</strong><small>{x.audience} · {x.status}</small></span>{canPublish&&<button onClick={()=>publish(x.id)}>Publish</button>}</div>):<p className="muted">No draft notices.</p>}</section></section>}
 <section className="two-column" style={{marginTop:18}}><section className="panel"><h2>Published notices</h2>{rows.length?rows.map(x=><div className="simple-row" key={x.id}><span><strong>{x.title}</strong><small>{x.audience}</small><p>{x.body}</p></span></div>):<p className="muted">No published notices.</p>}</section>
 <section className="panel"><h2>My notifications</h2>{notifications.length?notifications.map(x=><div className="simple-row" key={x.id}><span><strong>{x.title}</strong><small>{x.status}</small><p>{x.body}</p></span>{x.status!=="READ"&&<button onClick={()=>markRead(x.id)}>Mark read</button>}</div>):<p className="muted">No notifications.</p>}</section></section>
 </main>
}