"use client";
import {FormEvent,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {apiFetch,isAuthError} from "../../lib/api";

export default function Campus(){
 const router=useRouter();const [me,setMe]=useState<any>(null);const [integrations,setIntegrations]=useState<any[]>([]);const [grievances,setGrievances]=useState<any[]>([]);const [assets,setAssets]=useState<any[]>([]);
 const [g,setG]=useState({category:"GENERAL",subject:"",description:""});const [integration,setIntegration]=useState({kind:"PAYMENTS",provider:"",config_ref:""});const [asset,setAsset]=useState({asset_code:"",name:"",category:"GENERAL"});
 const [error,setError]=useState("");const [message,setMessage]=useState("");
 async function load(){try{const u=await apiFetch("/auth/me");setMe(u.data);const p=u.data.permissions as string[];if(p.includes("integrations.view"))setIntegrations((await apiFetch("/integrations")).data);if(p.includes("grievances.manage"))setGrievances((await apiFetch("/grievances")).data);if(p.includes("assets.manage"))setAssets((await apiFetch("/assets")).data)}catch(e){if(isAuthError(e))router.replace("/login");else setError(e instanceof Error?e.message:"Unable to load campus operations")}}useEffect(()=>{load()},[]);
 async function submitGrievance(e:FormEvent){e.preventDefault();setError("");try{await apiFetch("/grievances",{method:"POST",body:JSON.stringify(g)});setG({category:"GENERAL",subject:"",description:""});setMessage("Grievance submitted.");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to submit grievance")}}
 async function createIntegration(e:FormEvent){e.preventDefault();try{await apiFetch("/integrations",{method:"POST",body:JSON.stringify({...integration,config_ref:integration.config_ref||null})});setIntegration({kind:"PAYMENTS",provider:"",config_ref:""});setMessage("Integration created.");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to create integration")}}
 async function toggleIntegration(id:string){try{await apiFetch("/integrations/"+id+"/toggle",{method:"POST"});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to update integration")}}
 async function createAsset(e:FormEvent){e.preventDefault();try{await apiFetch("/assets",{method:"POST",body:JSON.stringify(asset)});setAsset({asset_code:"",name:"",category:"GENERAL"});setMessage("Asset created.");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to create asset")}}
 async function updateAsset(id:string,status:string){try{await apiFetch("/assets/"+id+"/status",{method:"PATCH",body:JSON.stringify({status})});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to update asset")}}
 async function updateGrievance(id:string,status:string){try{await apiFetch("/grievances/"+id+"/status",{method:"PATCH",body:JSON.stringify({status})});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to update grievance")}}
 const p=me?.permissions||[];const canViewIntegrations=p.includes("integrations.view"),canManageIntegrations=p.includes("integrations.manage"),canManageGrievances=p.includes("grievances.manage"),canManageAssets=p.includes("assets.manage");
 return <main className="module-page"><header><div><p className="eyebrow">CAMPUS OPERATIONS</p><h1>Campus Services</h1><p className="muted">Grievances, assets and provider-independent integrations.</p></div><button className="secondary" onClick={()=>router.push("/dashboard")}>Dashboard</button></header>{message&&<p className="status">{message}</p>}{error&&<p className="error">{error}</p>}
 <section className="two-column"><form className="panel" onSubmit={submitGrievance}><h2>Submit grievance</h2><label>Category<input value={g.category} onChange={e=>setG({...g,category:e.target.value})}/></label><label>Subject<input value={g.subject} onChange={e=>setG({...g,subject:e.target.value})} required/></label><label>Description<textarea value={g.description} onChange={e=>setG({...g,description:e.target.value})} required/></label><button>Submit</button></form>
 {canManageIntegrations&&<form className="panel" onSubmit={createIntegration}><h2>Add integration</h2><label>Kind<input value={integration.kind} onChange={e=>setIntegration({...integration,kind:e.target.value})} required/></label><label>Provider<input value={integration.provider} onChange={e=>setIntegration({...integration,provider:e.target.value})} required/></label><label>Config reference<input value={integration.config_ref} onChange={e=>setIntegration({...integration,config_ref:e.target.value})}/></label><button>Create integration</button></form>}</section>
 {canViewIntegrations&&<section className="panel" style={{marginTop:18}}><h2>Integrations</h2>{integrations.length?integrations.map(x=><div className="simple-row" key={x.id}><span><strong>{x.kind}</strong><small>{x.provider}</small></span><span>{canManageIntegrations?<button onClick={()=>toggleIntegration(x.id)}>{x.enabled?"Disable":"Enable"}</button>:<span className="status-pill">{x.enabled?"ENABLED":"DISABLED"}</span>}</span></div>):<p className="muted">No integrations configured.</p>}</section>}
 {canManageAssets&&<section className="two-column" style={{marginTop:18}}><form className="panel" onSubmit={createAsset}><h2>Add asset</h2><label>Asset code<input value={asset.asset_code} onChange={e=>setAsset({...asset,asset_code:e.target.value})} required/></label><label>Name<input value={asset.name} onChange={e=>setAsset({...asset,name:e.target.value})} required/></label><label>Category<input value={asset.category} onChange={e=>setAsset({...asset,category:e.target.value})} required/></label><button>Create asset</button></form><section className="panel"><h2>Assets</h2>{assets.length?assets.map(x=><div className="simple-row" key={x.id}><span><strong>{x.name}</strong><small>{x.asset_code} · {x.category}</small></span><select value={x.status} onChange={e=>updateAsset(x.id,e.target.value)}><option>ACTIVE</option><option>INACTIVE</option><option>MAINTENANCE</option><option>RETIRED</option></select></div>):<p className="muted">No assets.</p>}</section></section>}
 {canManageGrievances&&<section className="panel" style={{marginTop:18}}><h2>Grievance queue</h2>{grievances.length?grievances.map(x=><div className="simple-row" key={x.id}><span><strong>{x.subject}</strong><small>{x.category}</small><p>{x.description}</p></span><select value={x.status} onChange={e=>updateGrievance(x.id,e.target.value)}><option>OPEN</option><option>IN_PROGRESS</option><option>RESOLVED</option><option>CLOSED</option></select></div>):<p className="muted">No grievances.</p>}</section>}
 </main>}